# Generated by Django 3.0.5 on 2020-06-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20200625_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getmycars',
            name='year',
        ),
    ]
